import { type NextPage } from "next";
import Head from "next/head";
import { SignIn, UserButton, useUser } from "@clerk/nextjs"
import { api } from "~/utils/api";

const Home: NextPage = () => {
  const user = useUser()
  const { data } = api.images.getAll.useQuery()
  
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div>
          {!user.isSignedIn && <SignIn />}
          {user.isSignedIn && <UserButton />}
        </div>
        <div>
          {data?.map((image) => (<div key={image.id}>{image.content}</div>))}
        </div>
      </main>
    </>
  );
};

export default Home;